language: cpp
dist: trusty
osx_image: xcode12.2

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake; fi

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      # RANDR
      - xorg-dev
      - libxinerama-dev
      - libxrandr-dev
      - libgl1-mesa-dev

script:
     - cd ${TRAVIS_BUILD_DIR}
     - mkdir -p build
     - cd build
     - cmake ../
     - make

