language: cpp
dist: xenial

os:
  - linux

compiler:
  - gcc
  - clang

install:
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.14.3/cmake-3.14.3-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      echo ${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

addons:
  apt:
    packages:
      # RANDR
      - xorg-dev
      - libxinerama-dev
      - libxrandr-dev
      - libgl1-mesa-dev

script:
     - cd ${TRAVIS_BUILD_DIR}
     - mkdir -p build
     - cd build
     - cmake ../
     - make
